name: countries
description: Dart library for country data
version: 0.2.0
homepage: https://github.com/mathatan/countries

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_value: ^8.0.0
  computer: ^3.2.1
  universal_io: ^2.0.0
  fuzzywuzzy: ^0.2.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build: ^2.0.0
  build_runner: ^2.3.3
  source_gen: ^1.0.0
  built_value_generator: ^8.0.0
